sonar.projectKey=apply-the_canon
sonar.organization=apply-the
sonar.projectName=canon
sonar.sources=src,crates
sonar.exclusions=tests/**,target/**
sonar.host.url=https://sonarcloud.io
sonar.rust.lcov.reportPath=lcov.info
