sonar.projectKey=apply-the_canon
sonar.organization=apply-the

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=canon
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src,crates

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Coverage report
sonar.rust.lcov.reportPath=lcov.info
