use crate::observability::TelemetryPlan;

/// Generates the Markdown content for the 05-instrumentation-checklist.md
pub fn generate_instrumentation_checklist(plan: &TelemetryPlan) -> String {
    let mut out = String::new();
    out.push_str("# Observability Instrumentation Checklist\n\n");
    out.push_str("Ensure the following telemetry signals are properly implemented before closing the implementation phase.\n\n");

    for boundary in &plan.boundaries {
        out.push_str(&format!("## {}\n\n", boundary.boundary_name));
        out.push_str(&format!("- Failure Domain: `{}`\n", boundary.failure_domain));
        out.push_str(&format!("- Primary Consumer: `{}`\n\n", boundary.consumer));

        for signal in &boundary.signals {
            out.push_str(&format!(
                "- [ ] {:?}: `{}` - {}\n",
                signal.signal_type, signal.name, signal.description
            ));
        }
        out.push('\n');
    }

    if !plan.global_constraints.is_empty() {
        out.push_str("## Global Constraints\n\n");
        for constraint in &plan.global_constraints {
            out.push_str(&format!("- [ ] {}\n", constraint));
        }
    }

    out
}

/// Generates the Markdown content for the primary telemetry-plan.md
pub fn generate_telemetry_plan_markdown(plan: &TelemetryPlan) -> String {
    let mut out = String::new();
    out.push_str("# Telemetry Plan\n\n");
    out.push_str("Generated by Canon `observability-design` mode.\n\n");

    out.push_str("## System Boundaries\n\n");
    for boundary in &plan.boundaries {
        out.push_str(&format!("### {}\n\n", boundary.boundary_name));
        out.push_str("| Type | Name | Description |\n");
        out.push_str("|------|------|-------------|\n");
        for signal in &boundary.signals {
            out.push_str(&format!(
                "| {:?} | `{}` | {} |\n",
                signal.signal_type, signal.name, signal.description
            ));
        }
        out.push('\n');
    }

    out
}

/// Generates the Markdown content for SLO Alerts
pub fn generate_slo_alerts(slos: &[crate::observability::SloAlert]) -> String {
    let mut out = String::new();
    out.push_str("# SLO Alerts\n\n");

    out.push_str("| SLI Name | Threshold | Alert Destination |\n");
    out.push_str("|----------|-----------|-------------------|\n");

    for slo in slos {
        out.push_str(&format!(
            "| `{}` | `{}` | {} |\n",
            slo.sli_name, slo.threshold, slo.alert_destination
        ));
    }

    out
}

/// Generates the Markdown content for Runbook Stubs
pub fn generate_runbook_stubs(stubs: &[crate::observability::RunbookStub]) -> String {
    let mut out = String::new();
    out.push_str("# Runbook Playbooks\n\n");

    for stub in stubs {
        out.push_str(&format!("## Alert: `{}`\n\n", stub.alert_trigger));

        out.push_str("### If-This-Then-That Actions\n\n");
        for action in &stub.action_items {
            out.push_str(&format!("- [ ] {}\n", action));
        }
        out.push('\n');

        out.push_str(&format!(
            "### Escalation Path\n\n**Escalate to:** {}\n\n",
            stub.escalation_path
        ));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::observability::{
        BoundarySignalMap, RunbookStub, Signal, SignalType, SloAlert, TelemetryPlan,
    };

    #[test]
    fn test_generate_instrumentation_checklist() {
        let plan = TelemetryPlan {
            boundaries: vec![BoundarySignalMap {
                boundary_name: "B1".into(),
                failure_domain: "D1".into(),
                consumer: "C1".into(),
                signals: vec![Signal {
                    signal_type: SignalType::Log,
                    name: "S1".into(),
                    description: "Desc1".into(),
                }],
            }],
            global_constraints: vec!["GC1".into()],
        };
        let md = generate_instrumentation_checklist(&plan);
        assert!(md.contains("## B1"));
        assert!(md.contains("Failure Domain: `D1`"));
        assert!(md.contains("Primary Consumer: `C1`"));
        assert!(md.contains("Log: `S1` - Desc1"));
        assert!(md.contains("GC1"));
    }

    #[test]
    fn test_generate_telemetry_plan_markdown() {
        let plan = TelemetryPlan {
            boundaries: vec![BoundarySignalMap {
                boundary_name: "B1".into(),
                failure_domain: "D1".into(),
                consumer: "C1".into(),
                signals: vec![Signal {
                    signal_type: SignalType::Metric,
                    name: "M1".into(),
                    description: "Desc1".into(),
                }],
            }],
            global_constraints: vec![],
        };
        let md = generate_telemetry_plan_markdown(&plan);
        assert!(md.contains("### B1"));
        assert!(md.contains("| Metric | `M1` | Desc1 |"));
    }

    #[test]
    fn test_generate_slo_alerts() {
        let slos = vec![SloAlert {
            sli_name: "A".into(),
            threshold: "T".into(),
            alert_destination: "D".into(),
        }];
        let md = generate_slo_alerts(&slos);
        assert!(md.contains("`A` | `T` | D"));
    }

    #[test]
    fn test_generate_runbook_stubs() {
        let runbooks = vec![RunbookStub {
            alert_trigger: "T1".into(),
            action_items: vec!["Act1".into()],
            escalation_path: "Esc1".into(),
        }];
        let md = generate_runbook_stubs(&runbooks);
        assert!(md.contains("## Alert: `T1`"));
        assert!(md.contains("- [ ] Act1"));
        assert!(md.contains("**Escalate to:** Esc1"));
    }
}
