use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

/// The various types of adapters that provide execution capabilities to Canon.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AdapterKind {
    /// Local filesystem operations.
    Filesystem,
    /// Arbitrary shell command execution.
    Shell,
    /// Integration with GitHub Copilot CLI.
    CopilotCli,
    /// Model Context Protocol (MCP) tool invocation via stdio.
    McpStdio,
}

/// Specific types of actions an adapter can perform.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CapabilityKind {
    /// Reading files or metadata from the repository.
    ReadRepository,
    /// Inspecting git diffs or changes.
    InspectDiff,
    /// Reading Canon-specific artifacts.
    ReadArtifact,
    /// Emitting or publishing a governance artifact.
    EmitArtifact,
    /// Executing an arbitrary shell command.
    RunCommand,
    /// Generating text or code content.
    GenerateContent,
    /// Proposing a set of workspace edits.
    ProposeWorkspaceEdit,
    /// Performing a quality critique of content.
    CritiqueContent,
    /// Validating a claim with a specific tool.
    ValidateWithTool,
    /// Invoking a structured tool (e.g., via MCP).
    InvokeStructuredTool,
    /// Performing a bounded mutation (refactor, fix).
    ExecuteBoundedTransformation,
}

/// The phase of the governed execution lifecycle an invocation belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum InvocationOrientation {
    /// Gathering or reading context before generation.
    Context,
    /// Producing AI-generated content or workspace edits.
    Generation,
    /// Checking or verifying a claim or artifact.
    Validation,
    /// Deriving a canonical artifact from existing content.
    ArtifactDerivation,
}

/// How much of the workspace an invocation is permitted to change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MutabilityClass {
    /// The invocation makes no changes.
    ReadOnly,
    /// The invocation writes Canon governance artifacts only.
    ArtifactWrite,
    /// The invocation mutates a declared, bounded subset of the workspace.
    BoundedWorkspaceWrite,
    /// The invocation may mutate any part of the workspace.
    BroadWorkspaceWrite,
    /// The invocation changes state outside the local workspace (e.g. remote API).
    ExternalStateChange,
}

/// The trust level associated with an adapter's execution environment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TrustBoundaryKind {
    /// Deterministic local operations (e.g. file reads) with no external calls.
    LocalDeterministic,
    /// Local process execution (e.g. shell commands) with observable side effects.
    LocalProcess,
    /// AI model reasoning with non-deterministic, vendor-controlled outputs.
    AiReasoning,
    /// Structured tool calls to a remote service via a defined protocol.
    RemoteStructuredTool,
}

/// The provenance class of content produced by an invocation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LineageClass {
    /// Content produced by deterministic local tools; no AI generation involved.
    NonGenerative,
    /// Content generated by an AI model from a specific vendor family.
    AiVendorFamily,
    /// Content explicitly reviewed and accepted by a human reviewer.
    HumanReview,
}

/// The fully classified capability contract for a single adapter/capability pair.
///
/// Built by [`classify_capability`]; callers must not construct this manually
/// to avoid drift between capability classification and policy enforcement.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdapterCapability {
    /// The specific capability kind being described.
    pub kind: CapabilityKind,
    /// The phase of the execution lifecycle this capability belongs to.
    pub orientation: InvocationOrientation,
    /// How much of the workspace this capability may change.
    pub mutability: MutabilityClass,
    /// The trust level of the adapter providing this capability.
    pub trust_boundary: TrustBoundaryKind,
    /// The provenance class of content produced by this capability.
    pub lineage: LineageClass,
}

/// Returns the fully classified [`AdapterCapability`] for an `(adapter, capability)` pair.
///
/// This is the single authoritative mapping used by the orchestrator and
/// gatekeeper. All classification decisions must go through this function.
pub fn classify_capability(adapter: AdapterKind, capability: CapabilityKind) -> AdapterCapability {
    let trust_boundary = match adapter {
        AdapterKind::Filesystem => TrustBoundaryKind::LocalDeterministic,
        AdapterKind::Shell => TrustBoundaryKind::LocalProcess,
        AdapterKind::CopilotCli => TrustBoundaryKind::AiReasoning,
        AdapterKind::McpStdio => TrustBoundaryKind::RemoteStructuredTool,
    };

    let orientation = match capability {
        CapabilityKind::ReadRepository
        | CapabilityKind::InspectDiff
        | CapabilityKind::ReadArtifact
        | CapabilityKind::RunCommand => InvocationOrientation::Context,
        CapabilityKind::GenerateContent
        | CapabilityKind::ProposeWorkspaceEdit
        | CapabilityKind::ExecuteBoundedTransformation => InvocationOrientation::Generation,
        CapabilityKind::CritiqueContent | CapabilityKind::ValidateWithTool => {
            InvocationOrientation::Validation
        }
        CapabilityKind::EmitArtifact => InvocationOrientation::ArtifactDerivation,
        CapabilityKind::InvokeStructuredTool => InvocationOrientation::Context,
    };

    let mutability = match capability {
        CapabilityKind::ReadRepository
        | CapabilityKind::InspectDiff
        | CapabilityKind::ReadArtifact
        | CapabilityKind::RunCommand
        | CapabilityKind::GenerateContent
        | CapabilityKind::CritiqueContent
        | CapabilityKind::ValidateWithTool
        | CapabilityKind::InvokeStructuredTool => MutabilityClass::ReadOnly,
        CapabilityKind::EmitArtifact => MutabilityClass::ArtifactWrite,
        CapabilityKind::ExecuteBoundedTransformation => MutabilityClass::BoundedWorkspaceWrite,
        CapabilityKind::ProposeWorkspaceEdit => MutabilityClass::BroadWorkspaceWrite,
    };

    let lineage = match capability {
        CapabilityKind::GenerateContent
        | CapabilityKind::ProposeWorkspaceEdit
        | CapabilityKind::CritiqueContent => LineageClass::AiVendorFamily,
        _ => LineageClass::NonGenerative,
    };

    AdapterCapability { kind: capability, orientation, mutability, trust_boundary, lineage }
}

/// The observable side-effect class of a single adapter invocation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SideEffectClass {
    /// The invocation makes no changes; safe to replay.
    ReadOnly,
    /// The invocation writes a Canon governance artifact.
    ArtifactWrite,
    /// The invocation mutates workspace files.
    WorkspaceMutation,
    /// The invocation changes state outside the local workspace.
    ExternalStateChange,
}

/// A request to invoke a specific adapter capability, before policy has been applied.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdapterRequest {
    /// The adapter being requested.
    pub adapter: AdapterKind,
    /// The specific capability being requested.
    pub capability: CapabilityKind,
    /// One-line description of why this capability is being requested.
    pub purpose: String,
    /// The execution phase of this request, if explicitly known.
    pub orientation: Option<InvocationOrientation>,
    /// The trust boundary of the adapter, if explicitly known.
    pub trust_boundary: Option<TrustBoundaryKind>,
    /// The lineage class of content this request would produce.
    pub lineage: Option<LineageClass>,
    /// The observable side-effect this request would have.
    pub side_effect: SideEffectClass,
}

#[cfg(test)]
mod tests {
    use super::{
        AdapterKind, CapabilityKind, InvocationOrientation, LineageClass, MutabilityClass,
        TrustBoundaryKind, classify_capability,
    };

    #[test]
    fn copilot_generation_is_classified_as_ai_reasoning_generation() {
        let capability =
            classify_capability(AdapterKind::CopilotCli, CapabilityKind::GenerateContent);
        assert_eq!(capability.orientation, InvocationOrientation::Generation);
        assert_eq!(capability.trust_boundary, TrustBoundaryKind::AiReasoning);
        assert_eq!(capability.lineage, LineageClass::AiVendorFamily);
    }

    #[test]
    fn validation_tools_are_classified_as_validation_with_local_process_boundary() {
        let capability = classify_capability(AdapterKind::Shell, CapabilityKind::ValidateWithTool);
        assert_eq!(capability.orientation, InvocationOrientation::Validation);
        assert_eq!(capability.trust_boundary, TrustBoundaryKind::LocalProcess);
        assert_eq!(capability.mutability, MutabilityClass::ReadOnly);
    }

    #[test]
    fn mcp_stdio_emit_artifact_is_remote_structured_artifact_write() {
        let capability = classify_capability(AdapterKind::McpStdio, CapabilityKind::EmitArtifact);
        assert_eq!(capability.trust_boundary, TrustBoundaryKind::RemoteStructuredTool);
        assert_eq!(capability.orientation, InvocationOrientation::ArtifactDerivation);
        assert_eq!(capability.mutability, MutabilityClass::ArtifactWrite);
    }

    #[test]
    fn mcp_stdio_invoke_structured_tool_has_context_orientation() {
        let capability =
            classify_capability(AdapterKind::McpStdio, CapabilityKind::InvokeStructuredTool);
        assert_eq!(capability.orientation, InvocationOrientation::Context);
        assert_eq!(capability.mutability, MutabilityClass::ReadOnly);
        assert_eq!(capability.trust_boundary, TrustBoundaryKind::RemoteStructuredTool);
    }
}

/// A completed adapter invocation record, used for audit and evidence tracing.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdapterInvocation {
    /// The adapter that was invoked.
    pub adapter: AdapterKind,
    /// The capability that was exercised.
    pub capability: CapabilityKind,
    /// One-line description of the invocation purpose.
    pub purpose: String,
    /// The side-effect this invocation had.
    pub side_effect: SideEffectClass,
    /// Whether the invocation was permitted by policy.
    pub allowed: bool,
    /// When the invocation was recorded.
    pub occurred_at: OffsetDateTime,
}
